apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: django-web
    app.kubernetes.io/component: migrations
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-web
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: ilyag96/django-app
          imagePullPolicy: IfNotPresent
          command:
            - python
            - manage.py
            - migrate
          envFrom:
            - configMapRef:
                name: django-env