apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cron
  labels:
    app.kubernetes.io/name: django-web
    app.kubernetes.io/component: cronjob
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django-web
            app.kubernetes.io/component: cronjob
        spec:
          containers:
            - name: cronjob
              image: ilyag96/django-app
              imagePullPolicy: IfNotPresent
              command:
                - python
                - manage.py
                - clearsessions
              envFrom:
                - configMapRef:
                    name: django-env
          restartPolicy: Never