apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
  labels:
    app.kubernetes.io/name: django-web
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-web
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-web
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: django-web
          image: ilyag96/django-app
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: django-env

---

apiVersion: v1
kind: Service
metadata:
  name: django-web
  labels:
    app.kubernetes.io/name: django-web
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: django-web
    app.kubernetes.io/component: web